FROM ubuntu:22.04
RUN  apt-get update && \
apt-get install -y dotnet-sdk-8.0

RUN apt-get update && \
  apt-get install -y aspnetcore-runtime-8.0
RUN apt install -y nodejs
RUN apt install -y npm
RUN npm install -g typescript